package com.hwfamobile.media

import android.util.Base64
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * HwfaMedia — the on-device AES-256-GCM cipher for encrypted attachments.
 *
 * Implements the `MediaCipher` seam (packages/client media/) for React Native,
 * where Hermes has no `crypto.subtle`. Android's `AES/GCM/NoPadding` produces
 * ciphertext with the 16-byte GCM tag appended and uses a 128-bit tag by
 * default — byte-for-byte identical to the Web Crypto `WebCryptoMediaCipher`, so
 * media encrypted on Android decrypts on web/Node and vice versa.
 *
 * All bytes cross the bridge as base64 strings. The key/IV are generated by the
 * client and only ever exist in memory / inside the E2EE message body.
 */
class HwfaMediaModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = "HwfaMedia"

  private fun b64(bytes: ByteArray): String = Base64.encodeToString(bytes, Base64.NO_WRAP)
  private fun unb64(s: String): ByteArray = Base64.decode(s, Base64.NO_WRAP)

  private fun gcm(mode: Int, keyB64: String, ivB64: String): Cipher {
    val cipher = Cipher.getInstance("AES/GCM/NoPadding")
    val key = SecretKeySpec(unb64(keyB64), "AES")
    cipher.init(mode, key, GCMParameterSpec(128, unb64(ivB64)))
    return cipher
  }

  @ReactMethod
  fun randomBytes(length: Int, promise: Promise) {
    try {
      val out = ByteArray(length)
      SecureRandom().nextBytes(out)
      promise.resolve(b64(out))
    } catch (e: Exception) {
      promise.reject("randomBytes", e)
    }
  }

  @ReactMethod
  fun sha256(dataB64: String, promise: Promise) {
    try {
      val digest = MessageDigest.getInstance("SHA-256").digest(unb64(dataB64))
      promise.resolve(b64(digest))
    } catch (e: Exception) {
      promise.reject("sha256", e)
    }
  }

  /** Encrypt plaintext; returns base64 of ciphertext‖tag. */
  @ReactMethod
  fun encrypt(keyB64: String, ivB64: String, plaintextB64: String, promise: Promise) {
    try {
      val ct = gcm(Cipher.ENCRYPT_MODE, keyB64, ivB64).doFinal(unb64(plaintextB64))
      promise.resolve(b64(ct))
    } catch (e: Exception) {
      promise.reject("encrypt", e)
    }
  }

  /** Decrypt ciphertext‖tag; rejects on authentication failure. */
  @ReactMethod
  fun decrypt(keyB64: String, ivB64: String, ciphertextB64: String, promise: Promise) {
    try {
      val pt = gcm(Cipher.DECRYPT_MODE, keyB64, ivB64).doFinal(unb64(ciphertextB64))
      promise.resolve(b64(pt))
    } catch (e: Exception) {
      promise.reject("decrypt", e)
    }
  }
}
